#ifndef YANSHEEPLUGINGLOBAL_H
#define YANSHEEPLUGINGLOBAL_H

#include <QtCore/qglobal.h>

#if defined(YANSHEEPLUGIN_LIBRARY)
#  define YANSHEEPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define YANSHEEPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // YANSHEEPLUGINGLOBAL_H
